- name: Allow Kafka Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ kafka_exporter_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"