---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- import_tasks: preflight.yml
  tags:
    - install
    - configure

- import_tasks: install.yml
  tags:
    - install

- import_tasks: configure.yml
  tags:
    - configure

- name: Ensure Kafka Exporter systemd
  include_role:
    name: systemd-service
  vars:
    systemd_service: "{{ kafka_expoter_systemd }}"


